// Copyright 2006 The Closure Library Authors. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS-IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Copyright 2006 The Closure Library Authors. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS-IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
(function(wnd) {var h,l=this;function m(a){return void 0!==a}function aa(a){a.h=function(){return a.ca?a.ca:a.ca=new a}}
function ba(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function ca(a){return"array"==ba(a)}function n(a){return"string"==typeof a}function p(a){return"function"==ba(a)}function da(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}var ea="closure_uid_"+(1E9*Math.random()>>>0),fa=0;function ga(a,b,c){return a.call.apply(a.bind,arguments)}
function ha(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function q(a,b,c){q=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ga:ha;return q.apply(null,arguments)}
function r(a,b){function c(){}c.prototype=b.prototype;a.w=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.na=function(a,c,f){for(var g=Array(arguments.length-2),k=2;k<arguments.length;k++)g[k-2]=arguments[k];return b.prototype[c].apply(a,g)}};function ia(a,b){this.b=a;this.a=b?b:"";this.c=Error(a).stack||""}ia.prototype.toString=function(){return"wnd.core.Exception: "+this.b+(this.a?"("+this.a+")":"")};var t={mvc:{DataType:"MVCModelData"},View:{contentElementTypeAttr:"wnd_mvc_type"},PageStyles:{dataType:"page_and_template_styles"},StaticServerCategory:{templates:"templates",logo:"logo",background:"background",layoutBackground:"layoutBackground",socialIcons:"socialIcons",content:"content",microtemplate:"microtemplate",sectionBackgroundPrefix:"sectionBackground_",microtemplatePrefix:"microtemplate_"},Error:{unknownJs:{whiteList:"webnode keen google typekit newrelic nr-data.net".split(" ")}}};function u(a,b){ia.call(this,a);b||(b={error:{message:a,filename:"",lineno:"",stack:this.c}});if(w.isCms){var c;c=document.getElementsByTagName("script");for(var d=t.Error.unknownJs.whiteList,e="",f="",g=0,k=c.length;g<k;g++)(e=c[g].getAttribute("src"))&&!ja(d,e)&&(f+=e+"; ");(c=f)&&(b.error.unknownJs=c)}}r(u,ia);function ja(a,b){return 0<a.filter(function(a){return-1!==b.indexOf(a)}).length}
window.addEventListener("error",function(a){var b="";"undefined"!==typeof a.message&&(b=a.message);if(-1==b.indexOf("Script error")){var c="";"undefined"!==typeof a.filename&&(c=a.filename);var d="";"undefined"!==typeof a.lineno&&(d=a.lineno);new u(b,{error:{message:b,filename:c,lineno:d}})}},!1);var ka=null;var x={ImageSizeManager:{mvcID:"ImageSizeManager",DataType:"image_content_items",backgroundClass:"wnd-background-image",allowTypes:"wnd.pc.ImageBlock wnd.pc.PhotoGalleryBlock wnd.pc.PhotoImageBlock wnd.pc.LogoBlock wnd.pc.PhotoGallerySettingsForm wnd.pc.PhotoGallerySettingsPopupContent".split(" "),replaceTimeout:150},ImageTools:{identifier:"imageTools"},VideoLoaderManager:{mvcID:"VideoLoaderManager",className:"wnd-video-background",orientationClassName:{landscape:"orientation-landscape",portrait:"orientation-portrait"}},
UploadManager:{supportedImagesMime:["image/png","image/jpeg","image/gif"],supportedExifMime:["image/jpeg"],maxResizeImageDimension:1920,maxCanvasResolution:{low:4E3,normal:8E3,high:32E3},processImagesCount:1,imageOrientation:[1,2,3,4,5,6,7,8],imageTransformation:{1:{degree:0,flip:!1,ratio:!1},2:{degree:0,flip:!0,ratio:!1},3:{degree:180,flip:!0,ratio:!1},4:{degree:180,flip:!1,ratio:!1},5:{degree:90,flip:!0,ratio:!0},6:{degree:90,flip:!1,ratio:!0},7:{degree:-90,flip:!0,ratio:!0},8:{degree:-90,flip:!1,
ratio:!0}}},FilesystemPreviewSize:{detail:700,normal:450,small:200}};var la={DataObjectFactory:{gui_pages:"wnd.data.DbDataObject",gui_page_templates:"wnd.data.DbDataObject",filesystem_files:"wnd.data.DbDataObject",filesystem_dir:"wnd.data.DbDataObject",listing_items:"wnd.data.DbDataObject"},DataCollectionFactory:{fe_languages:"wnd.data.DbDataCollection",admin_languages:"wnd.data.DbDataCollection",gui_pages:"wnd.data.DbDataCollection",filesystem_files:"wnd.data.DbDataCollection",listing_items:"wnd.data.DbDataCollection",static_server:"wnd.data.StaticServerDataCollection",
tpl_page_templates:"wnd.data.DbDataCollection",page_and_template_styles:"wnd.data.PageAndTemplateStylesCollection",tpl_color_sets:"wnd.data.PrecachedDataCollection",tpl_forms:"wnd.data.DbDataCollection",tpl_form_fields:"wnd.data.DbDataCollection"}};var ma={FormManager:{mvcID:"FormManager"},template:{classNames:{fixed:"wnd-fixed",invalidFormField:"wnd-validate-error",formField:"wnd-form-field"}}};function na(a){na[" "](a);return a}na[" "]=function(){};function y(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function qa(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1}function ra(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b}function sa(a){for(var b in a)return!1;return!0}function ta(a){var b=ba(a);if("object"==b||"array"==b){if(a.clone)return a.clone();var b="array"==b?[]:{},c;for(c in a)b[c]=ta(a[c]);return b}return a}
function ua(a){var b=arguments.length;if(1==b&&ca(arguments[0]))return ua.apply(null,arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]=!0;return c};var va="closure_listenable_"+(1E6*Math.random()|0),wa=0;function xa(a,b,c,d,e){this.listener=a;this.a=null;this.src=b;this.type=c;this.K=!!d;this.b=e;this.ba=++wa;this.J=this.O=!1}function ya(a){a.J=!0;a.listener=null;a.a=null;a.src=null;a.b=null};ua("area base br col command embed hr img input keygen link meta param source track wbr".split(" "));var za=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};function Aa(a,b){return a<b?-1:a>b?1:0}Math.random();function Ba(a){return String(a).replace(/([A-Z])/g,"-$1").toLowerCase()};var Ca;a:{var Da=l.navigator;if(Da){var Ea=Da.userAgent;if(Ea){Ca=Ea;break a}}Ca=""}function z(a){return-1!=Ca.indexOf(a)};function Fa(){return z("iPhone")&&!z("iPod")&&!z("iPad")};var A=Array.prototype,Ga=A.indexOf?function(a,b,c){return A.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(n(a))return n(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},B=A.forEach?function(a,b,c){A.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=n(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},Ha=A.filter?function(a,b,c){return A.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=n(a)?
a.split(""):a,k=0;k<d;k++)if(k in g){var v=g[k];b.call(c,v,k,a)&&(e[f++]=v)}return e},Ja=A.reduce?function(a,b,c,d){d&&(b=q(b,d));return A.reduce.call(a,b,c)}:function(a,b,c,d){var e=c;B(a,function(c,g){e=b.call(d,e,c,g,a)});return e};function C(a,b){return 0<=Ga(a,b)}function Ka(a,b){var c=Ga(a,b),d;(d=0<=c)&&A.splice.call(a,c,1);return d}function La(a){return A.concat.apply(A,arguments)}function Ma(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};function Na(a){this.src=a;this.a={};this.b=0}Na.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.b++);var g=Oa(a,b,d,e);-1<g?(b=a[g],c||(b.O=!1)):(b=new xa(b,this.src,f,!!d,e),b.O=c,a.push(b));return b};Na.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=Oa(e,b,c,d);return-1<b?(ya(e[b]),A.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};
Na.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,ya(d[e]);delete this.a[c];this.b--}return b};function Pa(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=Oa(a,c,d,e));return-1<b?a[b]:null}Na.prototype.hasListener=function(a,b){var c=m(a),d=c?a.toString():"",e=m(b);return qa(this.a,function(a){for(var g=0;g<a.length;++g)if(!(c&&a[g].type!=d||e&&a[g].K!=b))return!0;return!1})};
function Oa(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.J&&f.listener==b&&f.K==!!c&&f.b==d)return e}return-1};function D(){return z("Edge")};function Qa(){return z("Opera")||z("OPR")}function Ra(){return z("Edge")||z("Trident")||z("MSIE")}function Sa(){return(z("Chrome")||z("CriOS"))&&!Qa()&&!Ra()};var Ta=Qa(),E=Ra(),Ua=z("Gecko")&&!(-1!=Ca.toLowerCase().indexOf("webkit")&&!D())&&!(z("Trident")||z("MSIE"))&&!D(),Va=-1!=Ca.toLowerCase().indexOf("webkit")&&!D();Va&&z("Mobile");z("Macintosh");z("Windows");z("Linux")||z("CrOS");var Wa=l.navigator||null;Wa&&(Wa.appVersion||"").indexOf("X11");z("Android");Fa();z("iPad");
function Xa(){var a=Ca;if(Ua)return/rv\:([^\);]+)(\)|;)/.exec(a);if(E&&D())return/Edge\/([\d\.]+)/.exec(a);if(E)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(Va)return/WebKit\/(\S+)/.exec(a)}function Ya(){var a=l.document;return a?a.documentMode:void 0}var Za=function(){if(Ta&&l.opera){var a=l.opera.version;return p(a)?a():a}var a="",b=Xa();b&&(a=b?b[1]:"");return E&&!D()&&(b=Ya(),b>parseFloat(a))?String(b):a}(),$a={};
function F(a){var b;if(!(b=$a[a])){b=0;for(var c=za(String(Za)).split("."),d=za(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",k=d[f]||"",v=/(\d*)(\D*)/g,Ia=/(\d*)(\D*)/g;do{var oa=v.exec(g)||["","",""],pa=Ia.exec(k)||["","",""];if(0==oa[0].length&&0==pa[0].length)break;b=Aa(0==oa[1].length?0:parseInt(oa[1],10),0==pa[1].length?0:parseInt(pa[1],10))||Aa(0==oa[2].length,0==pa[2].length)||Aa(oa[2],pa[2])}while(0==b)}b=$a[a]=0<=b}return b}
function ab(){return E&&(D()||9<=bb)}var cb=l.document,db=Ya(),bb=!cb||!E||!db&&D()?void 0:db||("CSS1Compat"==cb.compatMode?parseInt(Za,10):5);z("Firefox");Fa()||z("iPod");z("iPad");!z("Android")||Sa()||z("Firefox")||Qa()||z("Silk");Sa();!z("Safari")||Sa()||z("Coast")||Qa()||Ra()||z("Silk")||z("Android")||Fa()||z("iPad")||z("iPod");!E||ab();var eb=!E||ab(),fb=E&&!F("9");!Va||F("528");Ua&&F("1.9b")||E&&F("8")||Ta&&F("9.5")||Va&&F("528");Ua&&!F("8")||E&&F("9");("ontouchstart"in l||l.document&&document.documentElement&&"ontouchstart"in document.documentElement||l.navigator&&l.navigator.msMaxTouchPoints)&&(null===navigator.userAgent.match(/Chrome/)||null!==navigator.userAgent.match(/Chrome/)&&navigator.userAgent.match(/Android/));var gb=null!==navigator.userAgent.match(/Android|iPhone|iPad|iPod|BB10|BlackBerry|Windows Phone|IEMobile|Opera Mini/i);navigator.userAgent.match(/Chrome/);navigator.userAgent.match(/Firefox/);
null!==navigator.userAgent.match(/Safari/)&&navigator.userAgent.match(/Chrome/);null!==navigator.userAgent.match(/MSIE /)||navigator.userAgent.match(/Trident/);navigator.userAgent.match(/Edge\/[0-9]{2,}/);var hb=!E;function G(a,b){return hb&&a.dataset?b in a.dataset?a.dataset[b]:null:a.getAttribute("data-"+Ba(b))};function ib(a){if(a.classList)return a.classList;a=a.className;return n(a)&&a.match(/\S+/g)||[]}function jb(a,b){return a.classList?a.classList.contains(b):C(ib(a),b)}function kb(a,b){a.classList?a.classList.remove(b):jb(a,b)&&(a.className=Ha(ib(a),function(a){return a!=b}).join(" "))}function lb(a,b){var c=ma.template.classNames.invalidFormField;b?a.classList?a.classList.add(c):jb(a,c)||(a.className+=0<a.className.length?" "+c:c):kb(a,c)};!E||ab();!Ua&&!E||E&&ab()||Ua&&F("1.9.1");E&&F("9");E&&ab();function H(){0!=mb&&(nb[this[ea]||(this[ea]=++fa)]=this);this.i=this.i;this.v=this.v}var mb=0,nb={};H.prototype.i=!1;H.prototype.dispose=function(){if(!this.i&&(this.i=!0,this.m(),0!=mb)){var a=this[ea]||(this[ea]=++fa);delete nb[a]}};H.prototype.m=function(){if(this.v)for(;this.v.length;)this.v.shift()()};function I(){H.call(this);this.u=[]}r(I,H);I.prototype.m=function(){for(var a=0;a<this.u.length;a++)this.u[a]&&ob(this.u[a],this);I.w.m.call(this)};
function pb(a,b,c,d){var e=d?a:ta(a);null!=e||(e={});y(b,function(b,d){ca(e)&&0==e.length&&"number"!=typeof d&&(e={});if(null!=a&&"object"===typeof a[d]&&"object"===typeof b)e[d]=pb(e[d],b,c,!0);else if("object"===typeof b)e[d]=ta(b),c&&(c.changed=!0);else if(null==a||a[d]!==b)e[d]=b,c&&(c.changed=!0,"undefined"===typeof c.da&&(c.da={}),c.da[d]=b)});return e};function qb(){I.call(this);this.b={};this.c={}}r(qb,I);h=qb.prototype;h.L=null;h.T=!1;h.M=null;h.register=function(a,b){if(m(this.b[a]))throw new u('Class "'+a+'" already registered in factory');this.b[a]=b};h.get=function(a,b){if(this.T){var c=this.aa.apply(this,arguments);m(this.c[c])||(this.c[c]=this.Z.apply(this,arguments));return this.c[c]}return this.Z.apply(this,arguments)};
h.Z=function(a,b){null===this.L&&(this.L=this.f());var c;if(m(this.L[a]))c=this.L[a];else{if(null===this.M)throw new u('No valid class found for "'+a+'"');c=this.M}if(!m(this.b[c]))throw new u('Unregistered class "'+c+'" in factory');c=this.b[c];var d=Ma(arguments);d.unshift(null);return new (Function.prototype.bind.apply(c,d))};h.aa=function(a){return a};function J(){I.call(this);this.b={}}r(J,I);function rb(a,b,c,d){"undefined"==typeof a.b[b]&&(a.b[b]=[]);for(var e=0;e<a.b[b].length;e++)if(a.b[b][e].Y===c&&a.b[b][e].D===d)return;a.b[b].push({Y:c,D:d});d.u.push(a)}J.prototype.notify=function(a,b){var c;if("undefined"!=typeof this.b[a])for(var d=this.b[a].length,e=0;e<d&&(c=this.b[a][e],c.D instanceof H&&c.D.i||(c.Y.apply(c.D,arguments),m(this.b[a])));e++);};function ob(a,b){for(var c in a.b)a.b[c]=Ha(a.b[c],function(a){return a.D!=b})};function K(a,b,c){I.call(this);this.g=this[ea]||(this[ea]=++fa);this.b=a;this.c=b;this.a=null;c&&(this.a=c)}r(K,I);K.prototype.stopPropagation=function(){this.c="propagation_stopped"};function sb(a){a.c="children_propagation"}K.prototype.m=function(){this.a=null;K.w.m.call(this)};function tb(a,b){K.call(this,a,"parent_propagation",b)}r(tb,K);function ub(a,b,c,d){K.call(this,a,b,d);this.f=c}r(ub,K);function L(a){J.call(this);this.c=a||null;this.a=[];this.A=[];this.c&&this.c.a.push(this)}r(L,J);function vb(a,b){if(a.a){var c=a.a.indexOf(b);0<=c&&a.a.splice(c,1)}}function M(a,b){if("parent_propagation"==b.c)a.c?wb(a.c,b):b.stopPropagation();else if("children_propagation"==b.c)if(a.a)for(var c=a.a.length,d=0;d<c;d++)wb(a.a[d],b);else b.stopPropagation();"propagation_stopped"==b.c&&b.dispose()}function wb(a,b){-1==a.A.indexOf(b.g)&&(b.a&&b.a===a||a.handleEvent(b),a.A.push(b.g));M(a,b)}
L.prototype.handleEvent=function(a){a instanceof tb?this.I(a):a instanceof ub&&this.f(a)};L.prototype.f=function(){};L.prototype.I=function(){};L.prototype.m=function(){this.c&&vb(this.c,this);var a=Ma(this.a);B(a,function(a){a.dispose()},this);L.w.m.call(this)};function xb(a,b){L.call(this);this.g=b}r(xb,L);xb.prototype.f=function(a){"parent_propagation"==a.c?yb(N.h(),a):"children_propagation"==a.c&&C(this.g.ModuleDataEventFilter,a.f)&&M(this,a)};
xb.prototype.I=function(a){var b;var c=null,d="wnd.pc.TextBlock wnd.pc.InlineTextBlock wnd.pc.InlineDataBlock wnd.pc.ButtonBlock wnd.pc.FileBlock wnd.pc.LogoBlock wnd.pc.StyledInlineTextBlock".split(" ");b=a.a;if(null===b)b=c;else{var e=b.o();if("keenInfoAdd"==a.b)switch(e){case "wnd.pm.PagesAdminPopup":c="add_page_start";break;case "wnd.pc.InsertContentPopup":case "wnd.pc.EditZone":c="add_content";break;case "wnd.pc.LogoBlock":c="change_logo_start";break;case "wnd.pc.PageZone":c="drag_drop_start";
break;case "wnd.pc.SectionWrapper":c="new_section"}else if("keenInfoChange"==a.b){switch(e){case "wnd.pm.PagesTree":c="change_page_order";break;case "wnd.pc.EditSectionPopup":c="background_options_change";break;case "wnd.pc.LogoBlock":c="change_logo";break;case "wnd.pc.EditZone":c="drag_drop"}!c&&C(d,e)&&(c="change_text")}else if("keenInfoDelete"==a.b){switch(e){case "wnd.pm.PageEdit":c="delete_page"}c||(p(b.P)&&b.P()?c="delete_cell":p(b.X)&&b.X()?c="delete_microtemplate":p(b.V)&&b.V()&&(c="delete_content"));
!c&&C(["wnd.pc.BaseHover","wnd.pc.EditHover","wnd.pc.ButtonHover"],e)&&p(b.R)&&(c=b.R(),c=da(c)&&null!=c&&p(c.P)&&c.P()?"delete_cell_start":"delete_content_start");!c&&p(b.la)&&b.la()&&(c="delete_section");c||p(b.U)&&"wnd.pc.EditSectionPopup"==b.U().o()&&(c="delete_section_start")}else if("keenInfoOpen"==a.b)switch(e){case "wnd.pc.EditSectionPopup":c="background_options_start";break;case "wnd.pm.PagesAdminPopup":c="open_pages"}else"keenInfoEdit"==a.b&&C(d,e)&&(c="change_text_start");b=c}if("inspectletInfo1"==
a.b||"inspectletInfo2"==a.b||"inspectletInfo3"==a.b){window.__insp=window.__insp||[];if("inspectletInfo1"==a.b)switch(a.a.o()){case "wnd.tb.ToolbarContent":window.__insp.push(["tagSession","published"]);b="publish";break;case "wnd.pc.ImageBlock":window.__insp.push(["tagSession","edit image"]);break;case "wnd.pc.TextBlock":window.__insp.push(["tagSession","wysiwyg"]);break;case "wnd.pm.NewPageForm":window.__insp.push(["tagSession","added page"]);b="add_page";break;case "wnd.pm.PagesAdminPopup":window.__insp.push(["tagSession",
"opened pages"]);break;case "wnd.pc.InsertContentPopup":window.__insp.push(["tagSession","content add open"]);break;case "wnd.pc.EditSectionPopup":window.__insp.push(["tagSession","section remove"]);break;case "wnd.pc.MicroTemplate":window.__insp.push(["tagSession","microtemplate cell add"])}if("inspectletInfo2"==a.b)switch(a.a.o()){case "wnd.pc.InsertContentPopup":window.__insp.push(["tagSession","section add open"]);break;case "wnd.pc.EditSectionPopup":window.__insp.push(["tagSession","layout edit open"])}"inspectletInfo3"==
a.b&&"wnd.pc.EditSectionPopup"==a.a.o()&&window.__insp.push(["tagSession","section edit open"])}else b||("parent_propagation"==a.c&&sb(a),M(this,a));null!=zb&&p(zb.ea)&&b&&(b=a.a,a={data:{MVCType:b.o(),MVCId:b.B()}},(b=b.S?b.S():null)&&b.B&&(a.data.parentMVCId=b.B()))};function N(){J.call(this);this.a={}}r(N,J);aa(N);N.prototype.register=function(a,b){var c=new b(a);this.a[a]=c};N.prototype.init=function(){y(this.a,function(a,b){a.init();this.notify("onInit",b)},this)};N.prototype.get=function(a){if(!m(this.a[a]))throw new u("Invalid module namespace `"+a+"`");return this.a[a]};function yb(a,b){sb(b);y(a.a,function(a,d){void 0!=d&&a.f(b)},a)}
function Ab(a){var b=N.h();return Ja(ra(b.a),function(b,d){var e=m(d.g[a])?d.g[a]:null;return null===e?b:pb(b,e)},m(t[a])?t[a]:{},b)};function Bb(a){J.call(this);this.a=a}r(Bb,J);Bb.prototype.create=function(a){"undefined"==typeof O[this.a]&&(O[this.a]={});if("undefined"==typeof a.id){do a.id=Math.floor(1E4*Math.random()).toString();while("undefined"!=typeof O[this.a][a.id])}O[this.a][a.id]=a;a=a.id;Cb(P.h(),this.a);return a};Bb.prototype.delete=function(a){delete O[this.a][a];Cb(P.h(),this.a)};function Db(a){Bb.call(this,a)}r(Db,Bb);function Eb(){qb.call(this);this.T=!0;this.M="wnd.data.JSONDataObject"}r(Eb,qb);aa(Eb);Eb.prototype.f=function(){return pb(la.DataObjectFactory,Ab("DataObjectFactory"))};Eb.h().register("wnd.data.JSONDataObject",Db);function Fb(a){J.call(this);this.a=a}r(Fb,J);Fb.prototype.getData=function(a){if(!this.data)if("undefined"!=typeof O[this.a])this.data=O[this.a];else throw new u("Datatype "+this.a+" doesn't exist in JSONDataCollection (wnd.$data)");return a?m(this.data[a])?this.data[a]:void 0:this.data};function Gb(a){Fb.call(this,a)}r(Gb,Fb);function P(){qb.call(this);this.T=!0;this.M="wnd.data.JSONDataCollection";this.a={}}r(P,qb);aa(P);function Cb(a,b){m(a.a[b])&&y(a.a[b],function(a,d){var e=this.c[b+"_"+d];delete e.data;e.notify("onEraseCache")},a)}P.prototype.aa=function(a,b){return this.g.apply(this,arguments)};P.prototype.g=function(a,b){var c=b?JSON.stringify(b):"no_settings";m(this.a[a])||(this.a[a]={});this.a[a][c]=!0;return a+"_"+c};P.prototype.f=function(){return pb(la.DataCollectionFactory,Ab("DataCollectionFactory"))};
P.h().register("wnd.data.JSONDataCollection",Gb);function Q(a,b,c){J.call(this);this.f=a;this.g=b;var d=b.lastIndexOf(".");b.slice(0,d);c?this.a=c:this.a={id:a,create:{},properties:{}};"undefined"!=typeof this.a.create&&(a=this.a,R.h(),b=this.o(),c={},"undefined"!=typeof Hb[b]&&(c=ta(Hb[b]),Ib(c)),c.type=b,b=c,"undefined"!=typeof this.a.create.data&&(b=pb(b,this.a.create.data)),this.a.id&&(b.id=this.a.id),b=Jb(this).create(b,this.a.create),a.id=b);"undefined"===typeof this.a.properties&&(this.a.properties={});this.id=this.a.id}r(Q,J);h=Q.prototype;
h.s=t.mvc.DataType;h.G=null;function Jb(a){a.c||(a.c=Eb.h().get(a.s));return a.c}h.getData=function(){if(!this.G||m(this.a.collectionSettingsFunc))m(this.a.collectionSettings)?this.G=P.h().get(this.s,this.a.collectionSettings):m(this.a.collectionSettingsFunc)&&p(this.a.collectionSettingsFunc)?this.G=P.h().get(this.s,this.a.collectionSettingsFunc()):this.G=P.h().get(this.s);var a=this.G.getData();return this.id?a[this.id]:a};h.o=function(){return this.g};h.B=function(){return this.f};
h.m=function(){Jb(this).delete(this.id);Q.w.m.call(this)};function Kb(a,b,c){Q.call(this,a,b,c)}r(Kb,Q);function Lb(){var a=x.ImageSizeManager.DataType;return P.h().get(a)}function Mb(){var a=x.ImageSizeManager.DataType;return Eb.h().get(a)};function Nb(a,b){this.type=a;this.b=this.target=b;this.c=!1}Nb.prototype.stopPropagation=function(){this.c=!0};Nb.prototype.preventDefault=function(){};function S(a,b){Nb.call(this,a?a.type:"");this.b=this.target=null;this.clientY=this.clientX=0;this.a=this.state=null;a&&this.init(a,b)}r(S,Nb);S.prototype.init=function(a,b){this.type=a.type;this.target=a.target||a.srcElement;this.b=b;var c=a.relatedTarget;if(c&&Ua)try{na(c.nodeName)}catch(d){}this.clientX=void 0!==a.clientX?a.clientX:a.pageX;this.clientY=void 0!==a.clientY?a.clientY:a.pageY;this.state=a.state;this.a=a;a.defaultPrevented&&this.preventDefault()};
S.prototype.stopPropagation=function(){S.w.stopPropagation.call(this);this.a.stopPropagation?this.a.stopPropagation():this.a.cancelBubble=!0};S.prototype.preventDefault=function(){S.w.preventDefault.call(this);var a=this.a;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,fb)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};S.prototype.i=function(){return this.a};var Ob="closure_lm_"+(1E6*Math.random()|0),Pb={},Qb=0;
function Rb(a,b,c,d,e){if(ca(b)){for(var f=0;f<b.length;f++)Rb(a,b[f],c,d,e);return null}c=Sb(c);if(a&&a[va])a=Tb(a,b,c,d,e);else{if(!b)throw Error("Invalid event type");var f=!!d,g=Ub(a);g||(a[Ob]=g=new Na(a));c=g.add(b,c,!1,d,e);if(!c.a){d=Vb();c.a=d;d.src=a;d.listener=c;if(a.addEventListener)a.addEventListener(b.toString(),d,f);else if(a.attachEvent)a.attachEvent(Wb(b.toString()),d);else throw Error("addEventListener and attachEvent are unavailable.");Qb++}a=c}return a}
function Vb(){var a=Xb,b=eb?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b}function Yb(a){if("number"==typeof a||!a||a.J)return!1;var b=a.src;if(b&&b[va])return b.oa(a);var c=a.type,d=a.a;b.removeEventListener?b.removeEventListener(c,d,a.K):b.detachEvent&&b.detachEvent(Wb(c),d);Qb--;(c=Ub(b))?(d=a.type,d in c.a&&Ka(c.a[d],a)&&(ya(a),0==c.a[d].length&&(delete c.a[d],c.b--)),0==c.b&&(c.src=null,b[Ob]=null)):ya(a);return!0}
function Wb(a){return a in Pb?Pb[a]:Pb[a]="on"+a}function Zb(a,b,c,d){var e=!0;if(a=Ub(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.K==c&&!f.J&&(f=$b(f,d),e=e&&!1!==f)}return e}function $b(a,b){var c=a.listener,d=a.b||a.src;a.O&&Yb(a);return c.call(d,b)}
function Xb(a,b){if(a.J)return!0;if(!eb){var c;if(!(c=b))a:{c=["window","event"];for(var d=l,e;e=c.shift();)if(null!=d[e])d=d[e];else{c=null;break a}c=d}e=c;c=new S(e,this);d=!0;if(!(0>e.keyCode||void 0!=e.returnValue)){a:{var f=!1;if(0==e.keyCode)try{e.keyCode=-1;break a}catch(g){f=!0}if(f||void 0==e.returnValue)e.returnValue=!0}e=[];for(f=c.b;f;f=f.parentNode)e.push(f);for(var f=a.type,k=e.length-1;!c.c&&0<=k;k--){c.b=e[k];var v=Zb(e[k],f,!0,c),d=d&&v}for(k=0;!c.c&&k<e.length;k++)c.b=e[k],v=Zb(e[k],
f,!1,c),d=d&&v}return d}return $b(a,new S(b,this))}function Ub(a){a=a[Ob];return a instanceof Na?a:null}var ac="__closure_events_fn_"+(1E9*Math.random()>>>0);function Sb(a){if(p(a))return a;a[ac]||(a[ac]=function(b){return a.handleEvent(b)});return a[ac]};function T(a){H.call(this);this.c=a;this.a={}}r(T,H);var bc=[];function Tb(a,b,c,d,e){ca(c)||(c&&(bc[0]=c.toString()),c=bc);for(var f=0;f<c.length;f++){var g=Rb(b,c[f],d||a.handleEvent,e||!1,a.c||a);if(!g)break;a.a[g.ba]=g}return a}T.prototype.b=function(a,b,c,d,e){if(ca(b))for(var f=0;f<b.length;f++)this.b(a,b[f],c,d,e);else c=c||this.handleEvent,e=e||this.c||this,c=Sb(c),d=!!d,b=a&&a[va]?Pa(a,b,c,d,e):a?(a=Ub(a))?Pa(a,b,c,d,e):null:null,b&&(Yb(b),delete this.a[b.ba]);return this};
T.prototype.removeAll=function(){y(this.a,Yb);this.a={}};T.prototype.m=function(){T.w.m.call(this);this.removeAll()};T.prototype.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};function cc(a,b){this.b={};this.a=[];this.i=this.c=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)dc(this,arguments[d],arguments[d+1])}else if(a){if(a instanceof cc)d=a.H(),c=a.C();else{var c=[],e=0;for(d in a)c[e++]=d;d=c;c=ra(a)}for(e=0;e<d.length;e++)dc(this,d[e],c[e])}}h=cc.prototype;h.C=function(){ec(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};h.H=function(){ec(this);return this.a.concat()};
h.isEmpty=function(){return 0==this.c};h.clear=function(){this.b={};this.i=this.c=this.a.length=0};h.remove=function(a){return fc(this.b,a)?(delete this.b[a],this.c--,this.i++,this.a.length>2*this.c&&ec(this),!0):!1};function ec(a){if(a.c!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];fc(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.c!=a.a.length){for(var e={},c=b=0;b<a.a.length;)d=a.a[b],fc(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}}h.get=function(a,b){return fc(this.b,a)?this.b[a]:b};
function dc(a,b,c){fc(a.b,b)||(a.c++,a.a.push(b),a.i++);a.b[b]=c}h.forEach=function(a,b){for(var c=this.H(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};h.clone=function(){return new cc(this)};function fc(a,b){return Object.prototype.hasOwnProperty.call(a,b)};function U(a,b){this.x=m(a)?a:0;this.y=m(b)?b:0}U.prototype.clone=function(){return new U(this.x,this.y)};U.prototype.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};U.prototype.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};U.prototype.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};function gc(a,b){this.width=a;this.height=b}h=gc.prototype;h.clone=function(){return new gc(this.width,this.height)};h.isEmpty=function(){return!(this.width*this.height)};h.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};h.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};h.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function V(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d}h=V.prototype;h.clone=function(){return new V(this.left,this.top,this.width,this.height)};function hc(a,b){var c=Math.max(a.left,b.left),d=Math.min(a.left+a.width,b.left+b.width);if(c<=d){var e=Math.max(a.top,b.top),f=Math.min(a.top+a.height,b.top+b.height);if(e<=f)return new V(c,e,d-c,f-e)}return null}
h.difference=function(a){var b=hc(this,a);if(b&&b.height&&b.width){var b=[],c=this.top,d=this.height,e=this.left+this.width,f=this.top+this.height,g=a.left+a.width,k=a.top+a.height;a.top>this.top&&(b.push(new V(this.left,this.top,this.width,a.top-this.top)),c=a.top,d-=a.top-this.top);k<f&&(b.push(new V(this.left,k,this.width,f-k)),d=k-c);a.left>this.left&&b.push(new V(this.left,c,a.left-this.left,d));g<e&&b.push(new V(g,c,e-g,d));a=b}else a=[this.clone()];return a};
h.contains=function(a){return a instanceof V?this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height:a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height};h.ceil=function(){this.left=Math.ceil(this.left);this.top=Math.ceil(this.top);this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
h.floor=function(){this.left=Math.floor(this.left);this.top=Math.floor(this.top);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};h.round=function(){this.left=Math.round(this.left);this.top=Math.round(this.top);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function ic(a){var b=document;return n(a)?b.getElementById(a):a}function jc(a){var b=x.ImageSizeManager.backgroundClass,c=a||document;return c.querySelectorAll&&c.querySelector?c.querySelectorAll("."+b):kc(b,a)}
function kc(a,b){var c,d,e,f;c=document;c=b||c;if(c.querySelectorAll&&c.querySelector&&a)return c.querySelectorAll(""+(a?"."+a:""));if(a&&c.getElementsByClassName){var g=c.getElementsByClassName(a);return g}g=c.getElementsByTagName("*");if(a){f={};for(d=e=0;c=g[d];d++){var k=c.className;"function"==typeof k.split&&C(k.split(/\s+/),a)&&(f[e++]=c)}f.length=e;return f}return g}
function lc(){var a=window.document,a="CSS1Compat"==a.compatMode?a.documentElement:a.body;return new gc(a.clientWidth,a.clientHeight)};function mc(a){var b;try{b=a.getBoundingClientRect()}catch(c){return{left:0,top:0,right:0,bottom:0}}E&&a.ownerDocument.body&&(a=a.ownerDocument,b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+a.body.clientTop);return b}
function nc(a){if(1==a.nodeType)return a=mc(a),new U(a.left,a.top);var b=p(a.i),c=a;a.targetTouches&&a.targetTouches.length?c=a.targetTouches[0]:b&&a.a.targetTouches&&a.a.targetTouches.length&&(c=a.a.targetTouches[0]);return new U(c.clientX,c.clientY)}
function oc(a){var b=pc,c;a:{c=9==a.nodeType?a:a.ownerDocument||a.document;if(c.defaultView&&c.defaultView.getComputedStyle&&(c=c.defaultView.getComputedStyle(a,null))){c=c.display||c.getPropertyValue("display")||"";break a}c=""}if("none"!=(c||(a.currentStyle?a.currentStyle.display:null)||a.style&&a.style.display))return b(a);c=a.style;var d=c.display,e=c.visibility,f=c.position;c.visibility="hidden";c.position="absolute";c.display="inline";a=b(a);c.display=d;c.position=f;c.visibility=e;return a}
function pc(a){var b=a.offsetWidth,c=a.offsetHeight,d=Va&&!b&&!c;return m(b)&&!d||!a.getBoundingClientRect?new gc(b,c):(a=mc(a),new gc(a.right-a.left,a.bottom-a.top))}E&&F(12);function W(a,b){J.call(this);this.V=b;rb(this.V,"onUpdate",this.X,this)}r(W,J);W.prototype.a=!0;W.prototype.N=function(){return this.g};W.prototype.m=function(){this.g&&this.g.parentNode.removeChild(this.g);W.w.m.call(this)};W.prototype.X=function(){this.N()&&(this.notify("onBeforeRenderContent"),this.R(),this.notify("onRenderContent"))};function X(a,b,c){L.call(this,c);this.j=a;this.l=b;rb(this.j,"onUpdate",this.ma,this);rb(this.j,"onChangeId",this.ia,this);rb(this.l,"onRender",this.ja,this);rb(this.l,"onBeforeRenderContent",this.fa,this);rb(this.l,"onRenderContent",this.ka,this);a=this.j;m(a.a.create)&&null!=a.id&&this.j.s!=t.mvc.DataType&&(a=new ub("dataCreate","parent_propagation",this.j.s,this),M(this,a));this.N()&&!1===this.l.a&&(this.g=new T(this))}r(X,L);h=X.prototype;h.j=null;h.l=null;h.N=function(){return this.l.N()};
h.ma=function(a,b,c,d){this.j.s!=t.mvc.DataType&&d&&(a=new ub("dataUpdate","parent_propagation",this.j.s,this),M(this,a))};h.ia=function(){};h.ja=function(){this.notify("onViewRender")};h.m=function(){this.j.dispose();this.l.dispose();var a=R.h(),b=this.B();delete a.c[b];a.notify("onDisposeMVC",b);this.j.s!==t.mvc.DataType&&(a=new ub("dataDelete","parent_propagation",this.j.s,this),M(this,a));X.w.m.call(this)};h.o=function(){return this.j.o()};h.B=function(){return this.j.B()};
h.fa=function(){this.g&&this.g.removeAll()};h.ka=function(){this.g=new T(this)};function R(){J.call(this);this.a={};this.c={}}r(R,J);aa(R);R.prototype.register=function(a,b,c,d){if("undefined"==typeof this.a[a])this.a[a]={Model:b,View:c,Controller:d};else throw new u("MVC triad `"+a+"` already registered");};
R.prototype.create=function(a,b,c,d,e){if("undefined"==typeof this.a[b])throw new u("MVC triad `"+b+"` hasn't been registered");if("undefined"!=typeof this.c[a])throw new u("MVC triad `"+a+"` was already instancied");e=new this.a[b].Model(a,b,e);c=new this.a[b].View(c,e);b=new this.a[b].Controller(e,c,d);this.c[a]={Model:e,View:c,Controller:b};c.a&&(c.notify("onBeforeRenderContent"),c.R(),c.notify("onRender"),c.notify("onRenderContent"));this.notify("onCreateMVC",b);return b};
R.prototype.get=function(a){if("undefined"==typeof this.c[a])throw new u("MVC triad `"+a+"` hasn't been instancied");return this.c[a].Controller};function Ib(a){da(a.refs)&&ca(a.refDataTypes)&&(y(a.refs,function(b,c){-1===a.refDataTypes.indexOf(c)&&delete a.refs[c]}),sa(a.refs)&&delete a.refs,delete a.refDataTypes)};function qc(a,b){W.call(this,0,b);this.a=!1;this.c=null}r(qc,W);function rc(a){var b=lc(),c=new V(0,0,b.width,b.height);B(sc(a),function(a){var b=nc(a);a=oc(a);b=new V(b.x,b.y,a.width,a.height);(a=hc(c,b))&&0<a.width&&0<a.height&&(b=c.difference(b),c=b[0],B(b,function(a){if(c.height<a.height||c.width<a.width)c=a},this))},a);return c}function sc(a){null===a.c&&(a.c=document.getElementsByClassName(ma.template.classNames.fixed));return a.c}
function tc(a){for(var b=ma.template.classNames.formField;a&&!jb(a,b);)a=a.parentNode;return a};function uc(a,b,c){X.call(this,a,b,c);vc(this);wc(this);xc(this);yc(this)}r(uc,X);R.h().register("wnd.fe.FormManager",Q,qc,uc);h=uc.prototype;h.F={};h.W={};function vc(a){var b=document.querySelectorAll("input[type=checkbox][data-required]");B(b,function(a){zc(this,a.name,a);Rb(a,"change",q(function(a){Ac(this,a.target)},this));Ac(this,a)},a)}
function yc(a){B(document.forms,function(a){a.addEventListener("invalid",q(this.ha,this),!0);B(a.elements,function(a){C(["input","select","textarea"],a.nodeName.toLowerCase())&&Rb(a,"change",q(this.ga,this))},this)},a)}function zc(a,b,c){null!=a.F[b]||(a.F[b]=[]);a.F[b].push(c)}function Ac(a,b){if(null!=a.F[b.name]){var c=a.F[b.name],d=!1;B(c,function(a){d|=a.checked});B(c,function(a){a.required=!d})}}
function wc(a){var b=document.querySelectorAll("[data-filename-for]");B(b,function(a){var b=G(a,"filenameFor");b&&(this.W[b]=a)},a);b=document.querySelectorAll("input[type=file]");B(b,function(a){Rb(a,"change",q(function(a){Bc(this,a.target)},this));Bc(this,a)},a)}function Bc(a,b){null!=a.W[b.name]&&(a.W[b.name].innerHTML=b.value)}
function xc(a){var b=document.querySelectorAll("form");B(b,function(a){Rb(a,"submit",q(function(a){if(!1===Cc(this,a.target))return a.stopPropagation(),a.preventDefault(),!1},this))},a)}h.ga=function(a){var b=a.target;a=!b.checkValidity();b=tc(b);lb(b,a)};
h.ha=function(a){a=a.target;var b=rc(this.l),c=nc(a),d=oc(a),e,f=document;e=f.body;f=f.documentElement;e=new U(e.scrollLeft||f.scrollLeft,e.scrollTop||f.scrollTop);f=e.y;c.y<b.top?f=e.y+c.y-b.top:c.y+d.height>b.height&&(f=e.y+c.y+d.height+b.top-b.height);window.scrollTo(e.x,parseInt(f,10));a=tc(a);lb(a,!0)};
function Cc(a,b){var c=!0;B(b.elements,function(a){if(C(["input","select","textarea"],a.nodeName.toLowerCase())){var b;if(!(b=!a.checkValidity())&&(b="file"===a.type)){b=a.files[0];var f=b.name.substr(b.name.lastIndexOf(".")+1).toLowerCase();b=!1===(C(w.fileUploadAllowExtension,f)&&b.size<w.maxUserFormFileLimit)}a=tc(a);lb(a,b);b&&(c=!1)}},a);return c}h.I=function(a){if("scrollWindow"==a.b||"resizeWindow"==a.b)this.l.c=null};var Dc=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/;function Ec(a){if(Fc){Fc=!1;var b=l.location;if(b){var c=b.href;if(c&&(c=(c=Ec(c)[3]||null)?decodeURI(c):c)&&c!=b.hostname)throw Fc=!0,Error();}}return a.match(Dc)}var Fc=Va;
function Gc(a,b){for(var c=a.split("&"),d=0;d<c.length;d++){var e=c[d].indexOf("="),f=null,g=null;0<=e?(f=c[d].substring(0,e),g=c[d].substring(e+1)):f=c[d];b(f,g?decodeURIComponent(g.replace(/\+/g," ")):"")}};function Y(a,b){this.c=this.g=this.b="";this.v=null;this.u=this.a="";this.i=!1;var c;a instanceof Y?(this.i=m(b)?b:a.i,Hc(this,a.b),this.g=a.g,this.c=a.c,Ic(this,a.v),this.a=a.a,Jc(this,a.f.clone()),this.u=a.u):a&&(c=Ec(String(a)))?(this.i=!!b,Hc(this,c[1]||"",!0),this.g=Kc(c[2]||""),this.c=Kc(c[3]||"",!0),Ic(this,c[4]),this.a=Kc(c[5]||"",!0),Jc(this,c[6]||"",!0),this.u=Kc(c[7]||"")):(this.i=!!b,this.f=new Lc(null,0,this.i))}
Y.prototype.toString=function(){var a=[],b=this.b;b&&a.push(Mc(b,Nc,!0),":");if(b=this.c){a.push("//");var c=this.g;c&&a.push(Mc(c,Nc,!0),"@");a.push(encodeURIComponent(String(b)).replace(/%25([0-9a-fA-F]{2})/g,"%$1"));b=this.v;null!=b&&a.push(":",String(b))}if(b=this.a)this.c&&"/"!=b.charAt(0)&&a.push("/"),a.push(Mc(b,"/"==b.charAt(0)?Oc:Pc,!0));(b=this.f.toString())&&a.push("?",b);(b=this.u)&&a.push("#",Mc(b,Qc));return a.join("")};Y.prototype.clone=function(){return new Y(this)};
function Hc(a,b,c){a.b=c?Kc(b,!0):b;a.b&&(a.b=a.b.replace(/:$/,""))}function Ic(a,b){if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.v=b}else a.v=null}function Jc(a,b,c){b instanceof Lc?(a.f=b,Rc(a.f,a.i)):(c||(b=Mc(b,Sc)),a.f=new Lc(b,0,a.i))}function Kc(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""}function Mc(a,b,c){return n(a)?(a=encodeURI(a).replace(b,Tc),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null}
function Tc(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}var Nc=/[#\/\?@]/g,Pc=/[\#\?:]/g,Oc=/[\#\?]/g,Sc=/[\#\?@]/g,Qc=/#/g;function Lc(a,b,c){this.c=this.a=null;this.b=a||null;this.i=!!c}function Uc(a){a.a||(a.a=new cc,a.c=0,a.b&&Gc(a.b,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))}h=Lc.prototype;h.add=function(a,b){Uc(this);this.b=null;a=Vc(this,a);var c=this.a.get(a);c||dc(this.a,a,c=[]);c.push(b);this.c++;return this};
h.remove=function(a){Uc(this);a=Vc(this,a);return fc(this.a.b,a)?(this.b=null,this.c-=this.a.get(a).length,this.a.remove(a)):!1};h.clear=function(){this.a=this.b=null;this.c=0};h.isEmpty=function(){Uc(this);return 0==this.c};h.H=function(){Uc(this);for(var a=this.a.C(),b=this.a.H(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};
h.C=function(a){Uc(this);var b=[];if(n(a)){var c=a;Uc(this);c=Vc(this,c);fc(this.a.b,c)&&(b=La(b,this.a.get(Vc(this,a))))}else for(a=this.a.C(),c=0;c<a.length;c++)b=La(b,a[c]);return b};h.get=function(a,b){var c=a?this.C(a):[];return 0<c.length?String(c[0]):b};
h.toString=function(){if(this.b)return this.b;if(!this.a)return"";for(var a=[],b=this.a.H(),c=0;c<b.length;c++)for(var d=b[c],e=encodeURIComponent(String(d)),d=this.C(d),f=0;f<d.length;f++){var g=e;""!==d[f]&&(g+="="+encodeURIComponent(String(d[f])));a.push(g)}return this.b=a.join("&")};h.clone=function(){var a=new Lc;a.b=this.b;this.a&&(a.a=this.a.clone(),a.c=this.c);return a};function Vc(a,b){var c=String(b);a.i&&(c=c.toLowerCase());return c}
function Rc(a,b){b&&!a.i&&(Uc(a),a.b=null,a.a.forEach(function(a,b){var e=b.toLowerCase();b!=e&&(this.remove(b),this.remove(e),0<a.length&&(this.b=null,dc(this.a,Vc(this,e),Ma(a)),this.c+=a.length))},a));a.i=b};function Wc(a){a=a.b+"://"+a.c+"/";return a+"files"==w.staticFiles||C(w.staticCDNServers,a)}function Xc(a){return a.b+"://"+a.c+"/"==w.filesPath};function Yc(a,b){W.call(this,0,b);this.a=!1;this.A=null}r(Yc,W);function Zc(a){a=$c(a);for(var b=0;b<a.length;b++)if("IMG"===a[b].nodeName)if(gb)a[b].className=ad(parseInt(G(a[b],"videoWidth"),10),parseInt(G(a[b],"videoHeight"),10),a[b].parentNode.clientWidth,a[b].parentNode.clientHeight);else if(a[b].outerHTML=bd(a[b],cd(a[b])),w.isCms){var c=a[b];c.onended=function(){c.currentTime=0;c.pause()}}}
function cd(a){a.parentNode&&(a=a.parentNode);for(var b=0,c=0,d=a.offsetWidth,e=a.offsetHeight;a&&a!==document.body;)b+=a.offsetLeft,c+=a.offsetTop,a=a.offsetParent;a=c+e;b=Math.max(0,Math.min(d,window.pageXOffset+window.innerWidth-b,b+d-window.pageXOffset));c=Math.max(0,Math.min(e,window.pageYOffset+window.innerHeight-c,a-window.pageYOffset));return.2<b*c/(d*e)}
function ad(a,b,c,d){var e=x.VideoLoaderManager.className+" ",f=x.VideoLoaderManager.orientationClassName.landscape,g=x.VideoLoaderManager.orientationClassName.portrait;a=parseInt(a,10);b=parseInt(b,10);a>b&&c>d||a<b&&c<d?(c=Math.round(c*b/a),e=d<c?e+f:e+g):(d=Math.round(d*a/b),e=c<d?e+g:e+f);return e}
function bd(a,b){var c="<video ";(hb&&a.dataset?"video"in a.dataset:a.hasAttribute?a.hasAttribute("data-"+Ba("video")):a.getAttribute("data-"+Ba("video")))&&(c+='src="'+G(a,"video")+'" ');a.src&&(c+='poster="'+a.src+'" ');var d=parseInt(G(a,"videoWidth"),10),e=parseInt(G(a,"videoHeight"),10),f=ad(d,e,a.parentNode.clientWidth,a.parentNode.clientHeight),c=c+('class="'+f+'" ');b&&(c+="autoplay ");c+='data-video-width="'+d+'" data-video-height="'+e+'"';return c=w.isCms?c+">":c+"loop>"}
function $c(a){a.A=document.getElementsByClassName(x.VideoLoaderManager.className);return a.A};function dd(a,b,c){X.call(this,a,b,c);Zc(this.l)}r(dd,X);dd.prototype.I=function(a){if("scrollWindow"==a.b||"resizeWindow"==a.b){a=this.l.A;for(var b=0;b<a.length;b++)!1===w.isCms&&"VIDEO"===a[b].nodeName&&(cd(a[b])?a[b].paused&&a[b].play():a[b].paused||a[b].pause()),a[b].className=ad(parseInt(G(a[b],"videoWidth"),10),parseInt(G(a[b],"videoHeight"),10),a[b].parentNode.clientWidth,a[b].parentNode.clientHeight)}};R.h().register("wnd.static.VideoLoaderManager",Q,Yc,dd);function ed(){I.call(this);this.f={};this.c={};this.a=new T(this);this.b={}}r(ed,I);aa(ed);function fd(a,b,c,d,e){var f=a.f[b];if(null!=f&&!0===f.complete)null!=c&&a.g(f.src,c);else{var g;a.b[b]||(a.b[b]=1);g=b+("?t="+a.b[b]);if(!f){var k=new Y(g),f=new Image;if(Xc(k)||Wc(k)&&e)f.crossOrigin="anonymous";f.src=g;a.f[b]=f}!0===(null!=c)&&(g=q(a.g,a,g,c,d),Tb(a.a,f,"load",g,void 0),b=q(a.A,a,b,c,d,e),Tb(a.a,f,"error",b,void 0),m(d)&&(null!=a.c[d]&&a.a.b.apply(a.a,a.c[d]),a.c[d]=[f,"load",g]))}}
ed.prototype.g=function(a,b,c){b(a);null!=c&&(this.a.b.apply(this.a,this.c[c]),this.c[c]=null)};ed.prototype.A=function(a,b,c,d){new u("Image "+a+"?t="+this.b[a]+" was not loaded.");if(1==this.b[a]){var e=this.b,f=window.location.href+(new Date).toDateString();if(null===ka){for(var g,k=[],v=0;256>v;v++){g=v;for(var Ia=0;8>Ia;Ia++)g=g&1?3988292384^g>>>1:g>>>1;k[v]=g>>>0}ka=k}g=-1;for(k=0;k<f.length;k++)g=g>>>8^ka[(g^f.charCodeAt(k))&255];e[a]=(g^-1)>>>0;delete this.f[a];fd(this,a,b,c,d)}};function gd(a,b){W.call(this,0,b);this.a=!1;this.f=[]}r(gd,W);function hd(a,b){var c=ic(b);null!=c&&B(c.getElementsByTagName("IMG"),function(a){a.complete?id(a):a.onload=function(){id(this)}},a)}
function jd(a,b){var c=null;b&&(c=ic(b));c=jc(c);B(c,function(a){if(null!=a.style.backgroundImage&&!C(this.f,a)){var b=a.style.backgroundImage.slice(4,-1).replace(/"/g,""),c=new Y(b),g=kd(c,0);c.a=g;c=c.toString();b!=c&&(this.f.push(a),a=q(this.U,this,a),b=ed.h(),c=new Y(c),Jc(c,"",void 0),fd(b,c.toString(),a,void 0))}},a)}gd.prototype.U=function(a,b){var c=a.cloneNode(!1);c.style.backgroundImage="url("+b+")";a.parentNode&&a.parentNode.insertBefore(c,a.nextSibling);setTimeout(q(this.S,this,c,a),x.ImageSizeManager.replaceTimeout)};
gd.prototype.S=function(a,b){Ka(this.f,b);for(var c=b.firstChild,d=null;c;)d=c.nextSibling,a.appendChild(c),c=d;b&&b.parentNode&&b.parentNode.removeChild(b)};
function id(a){var b,c=0;b=a.clientWidth>a.clientHeight?a.clientWidth:a.clientHeight;b<=x.FilesystemPreviewSize.small?c=x.FilesystemPreviewSize.small:b>x.FilesystemPreviewSize.small&&b<=x.FilesystemPreviewSize.normal?c=x.FilesystemPreviewSize.normal:b>x.FilesystemPreviewSize.normal&&b<=x.FilesystemPreviewSize.detail&&(c=x.FilesystemPreviewSize.detail);b=c;var c=new Y(a.getAttribute("src")),d=kd(c,b);if(d!=c.a){c.a=d;if(a.hasAttribute("width")||a.hasAttribute("height")){var e=a.hasAttribute("width")?
parseInt(a.getAttribute("width"),10):a.naturalWidth,f=a.hasAttribute("height")?parseInt(a.getAttribute("height"),10):a.naturalHeight;e>f?(d=b,b=Math.round(b/e*f)):d=Math.round(b/f*e);a.hasAttribute("width")&&a.setAttribute("width",d);a.hasAttribute("height")&&a.setAttribute("height",b)}a.setAttribute("src",c.toString())}}
function kd(a,b){var c,d=a.a.split("/");if(Xc(a)){c="/"+d[1]+"/";if(3==d.length&&0<b)return c+b+"/"+d[2];if(4==d.length&&b!=d[2])return c+(0<b?b+"/":"")+d[3]}else if(Wc(a)){c="/files/"+d[2]+"/"+d[3]+"/";var e=(new Y(a.a)).a,f=e.lastIndexOf("/")+1,e=e.slice(f).replace(/\.+/g,"."),f=e.lastIndexOf(".");if("svg"==(0>=f?"":e.substr(f+1))||5==d.length&&0<b)return c+d[4];if(6==d.length&&b!=d[4])return c+(0<b?b+"/":"")+d[5]}return a.a};function ld(a,b,c){X.call(this,a,b,c);md(this)}r(ld,X);ld.prototype.I=function(a){switch(a.b){case "contentMove":case "photoGalleryChange":a.a&&nd(a.a.o())&&hd(this.l,a.a.j.id);break;case "resizeWindow":md(this);break;case "sectionCreated":case "microTemplateCellCreated":a.a&&hd(this.l,a.a.j.id);break;case "sectionBackgroundChange":a.a&&jd(this.l,a.a.j.id);break;case "pageBackgroundChange":jd(this.l)}};
ld.prototype.f=function(a){if(a.a&&"content_items"==a.f)switch(a.b){case "dataCreate":var b=a.a.j.id;a=a.a.o();nd(a)&&Mb().create({id:b,type:a});break;case "dataDelete":b=a.a.j.id;nd(a.a.o())&&Mb().delete(b);break;case "dataUpdate":nd(a.a.o())&&hd(this.l,a.a.j.id)}};function md(a){var b=Lb().getData();null!=b&&y(b,function(a){nd(a.type)&&hd(this.l,a.id)},a);jd(a.l)}function nd(a){return C(x.ImageSizeManager.allowTypes,a)}R.h().register("wnd.static.ImageSizeManager",Kb,gd,ld);function od(){xb.call(this,0,ma)}r(od,xb);od.prototype.init=function(){R.h().create(x.ImageSizeManager.mvcID,"wnd.static.ImageSizeManager",document.body,this);R.h().create(x.VideoLoaderManager.mvcID,"wnd.static.VideoLoaderManager",document.body,this);R.h().create(ma.FormManager.mvcID,"wnd.fe.FormManager",document.body,this)};function pd(){var a=N.h().get("wnd.fe"),b=new tb("resizeWindow",a);sb(b);M(a,b)}function qd(){var a=N.h().get("wnd.fe"),b=new tb("scrollWindow",a);sb(b);M(a,b)}window.onload=function(){window.onresize=pd;window.onscroll=qd;O=window.wnd.$data;w=window.wnd.$system;N.h().register("wnd.fe",od);N.h().init()};if(!O)var O={};if(!Hb)var Hb={};if(!w)var w={};if(!zb)var zb={};zb.ea=function(){};var rd=zb,sd=["wnd","keen"],Z=l;sd[0]in Z||!Z.execScript||Z.execScript("var "+sd[0]);
for(var td;sd.length&&(td=sd.shift());)!sd.length&&m(rd)?Z[td]=rd:Z[td]?Z=Z[td]:Z=Z[td]={};
}({}));